title: Saransh Agarwal
baseURL: /
params:
  footer:
    content: '&copy 2019 Saransh Agarwal. Made with Netlify, Github and Hugo.'
    links: []
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: /images/hednqoee_400x400.jpg
    tagline: ''
    title: Saransh Agarwal
  layout_style: overflow
  palette: blue
disableKinds:
  - RSS
