title: Saransh Agarwal
baseURL: /
params:
  footer:
    content: '&copy 2019 Saransh Agarwal; All rights reserved.'
    links:
      - new_window: false
        text: 'Made with Netlify, Github and Hugo.'
        url: ''
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: /images/avatar.png
    tagline: Header Tagline
    title: Saransh Agarwal
  layout_style: overflow
  palette: blue
disableKinds:
  - RSS
